### ISSUE TITLE
Typo in 'avoid-detectcores' post?

### ISSUE THREAD

**Issue by PeteHaitch** [HenrikBengtsson/jottr.org-blogdown#24]
Is the `ncores <- max(1L, detectCores(), na.rm = TRUE)` line here correct?

https://github.com/HenrikBengtsson/jottr.org-blogdown/blob/b38055f879c41b9d98363326b18978760254de9d/content/post/2022-12-05-avoid-detectCores.md?plain=1#L213-L219

I was expecting something about using the `omit` argument of `parallelly::availableCores()`.

**Comment by HenrikBengtsson** [comment]
Oh, thanks for spotting this. I must have changed in by mistake, cf. https://github.com/HenrikBengtsson/jottr.org-blogdown/commit/1657b9ba3f9a156206d6696a10875fd30bb0a6ae.  Fixed now.
